[package]
name = "dnschecker"
version = "0.1.0"
description = "DNSChecker desktop app"
authors = ["DNSChecker"]
edition = "2021"

[lib]
name = "dnschecker_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
hickory-proto = "0.26.1"
hickory-resolver = { version = "0.26.1", features = ["https-ring", "rustls-platform-verifier", "system-config", "tls-ring", "tokio"] }
humantime = "2.3.0"
rustls = "0.23.40"
rustls-platform-verifier = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2.9.4", features = [] }
tokio = { version = "1.48.0", features = ["macros", "net", "rt", "sync", "time"] }
tokio-rustls = "0.26.4"
