[package]
name = "dnschecker"
version = "0.1.0"
description = "DNSChecker desktop app"
authors = ["DNSChecker"]
edition = "2021"

[lib]
name = "dnschecker_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2.9.4", features = [] }
